### ISSUE TITLE
Enhancement: z-index calculation

### ISSUE THREAD

**Issue by MelSumner** [hashicorp/design-system#114]
## Summary

Automate (as much as we can) z-index so we don't try to juggle/ remember the numbers. 

## Potential Solution

In sass, make a variable with a list of named z-index layers, and a function that accepts a name and returns what number it is in the list, that way you’re not trying to remember a number; when new things are added to the list, everything will adjust automatically:

```scss
$z: base, header, tooltip, dialog, alert;
.alert { z-index: z(alert); }
```
